# Generated by features/scripts/update-scenario-names.sh
$scenario_names = [
  'BadMemoryAccessScenario',
  'CancelSessionScenario',
  'MaxConfigCrashScenario',
  'ModifyCrumbsScenario',
  'ModifySessionScenario',
  'NotifyScenario',
  'OpenLevelBreadcrumbsScenario',
  'PauseSessionScenario',
  'ResumeSessionScenario',
]
