version: '3.6'
services:
  android-maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v5-cli
    environment:
      DEBUG:
      BUILDKITE:
      BUILDKITE_PIPELINE_NAME:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      SAUCE_LABS_USERNAME:
      SAUCE_LABS_ACCESS_KEY:
    volumes:
      - ./features/fixtures/mobile/Binaries/Android:/app/build
      - ./features/:/app/features/
      - ./maze_output:/app/maze_output
  cocoa-maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v5-cli
    environment:
      DEBUG:
      VERBOSE:
      BUILDKITE:
      BUILDKITE_PIPELINE_NAME:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
    volumes:
      - ./features/fixtures/mobile/Binaries/IOS:/app/build
      - ./features/:/app/features/
      - ./maze_output:/app/maze_output
