agents:
  queue: opensource

steps:
  - name: 'Append Unreal 5.0 Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.0.yml

  - name: 'Append Unreal 5.1 Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.1.yml

  - name: 'Append Unreal 5.2 Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.2.yml

  - name: 'Append Unreal 5.3 Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.3.yml
