steps:
  #
  # Build Plugins
  #

  # UE 4.25
  - label: ':mac: Build Plugin - UE 4.25'
    agents:
      queue: opensource-mac-cocoa-10.15
    env:
      UE_VERSION: "4.25"
      DEVELOPER_DIR: "/Applications/Xcode12.app"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - make package
    plugins:
      artifacts#v1.5.0:
        upload:
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    artifact_paths: [Build/Plugin/*.zip]
    timeout_in_minutes: 30
    key: plugin_4_25

  # UE 4.26
  - label: ':mac: Build Plugin - UE 4.26'
    agents:
      queue: opensource-arm-mac-cocoa-12
    env:
      UE_VERSION: "4.26"
      DEVELOPER_DIR: "/Applications/Xcode13.app"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - make package
    plugins:
      artifacts#v1.5.0:
        upload:
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    artifact_paths: [Build/Plugin/*.zip]
    timeout_in_minutes: 30
    key: plugin_4_26

  # UE 5.0EA
  - label: ':mac: Build Plugin - UE 5.0EA'
    agents:
      queue: opensource-mac-cocoa-10.15
    env:
      UE_VERSION: "5.0EA"
      DEVELOPER_DIR: "/Applications/Xcode12.app"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - make package
    plugins:
      artifacts#v1.5.0:
        upload:
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    artifact_paths: [Build/Plugin/*.zip]
    timeout_in_minutes: 30
    key: plugin_5_0ea
