agents:
  queue: macos

steps:
  - label: 'Append Unreal 5.0 Pipeline'
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.0.yml

  - label: 'Append Unreal 5.1 Pipeline'
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.1.yml

  - label: 'Append Unreal 5.2 Pipeline'
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.2.yml

  - label: 'Append Unreal 5.3 Pipeline'
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.3.yml
