steps:
  # UE 4.27 Mac
  - label: 'Build Plugin - 4.27 Mac'
    env:
      UE_VERSION: "4.27"
      DEVELOPER_DIR: "/Applications/Xcode13.2.1.app"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - make package
    plugins:
      artifacts#v1.5.0:
        upload:
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    artifact_paths: [Build/Plugin/*.zip]
    timeout_in_minutes: 60
    agents:
      queue: ms-arm-12-4
