agents:
  queue: macos-12-arm

steps:
  #
  # Build Plugins
  #

  # Unreal Engine 5.0 - macOS
  - label: 'Build Plugin - 5.0 Mac'
    env:
      UE_VERSION: "5.0"
      DEVELOPER_DIR: "/Applications/Xcode13.2.1.app"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - make package
    plugins:
      artifacts#v1.5.0:
        upload:
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    artifact_paths: [ Build/Plugin/*.zip ]
    timeout_in_minutes: 60
    key: plugin_5_0

  #
  # Build Test Fixtures
  #

  # Unreal Engine 5.0 - Android
  - name: ':android: Build E2E - 5.0 Android'
    depends_on: plugin_5_0
    env:
      UE_VERSION: "5.0"
      DEVELOPER_DIR: "/Applications/Xcode13.2.1.app"
    plugins:
      artifacts#v1.5.0:
        download: Build/Plugin/Bugsnag-*-UE_5.0-macOS.zip
        upload:
          - build/TestFixture-Android-Shipping-5.0-arm64.apk
          - build/TestFixture-Android-Shipping-5.0-armv7.apk
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - features/scripts/build-fixture.sh Android
    timeout_in_minutes: 60
    key: android_fixture_5_0

  # Unreal Engine 5.0 - iOS
  - name: ':ios: Build E2E - 5.0 iOS'
    depends_on: plugin_5_0
    env:
      UE_VERSION: "5.0"
      DEVELOPER_DIR: "/Applications/Xcode13.2.1.app"
    plugins:
      artifacts#v1.5.0:
        download: Build/Plugin/Bugsnag-*-UE_5.0-macOS.zip
        upload:
          - build/TestFixture-IOS-Shipping-5.0.dSYM
          - build/TestFixture-IOS-Shipping-5.0.ipa
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - features/scripts/build-fixture.sh IOS
    timeout_in_minutes: 60
    key: ios_fixture_5_0

  # Unreal Engine 5.0 - macOS
  - name: ':mac: Build E2E - 5.0 macOS'
    depends_on: plugin_5_0
    env:
      UE_VERSION: "5.0"
      DEVELOPER_DIR: "/Applications/Xcode13.2.1.app"
    plugins:
      artifacts#v1.5.0:
        download: Build/Plugin/Bugsnag-*-UE_5.0-macOS.zip
        upload:
          - TestFixture-macOS-5.0.zip
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - features/scripts/build-fixture.sh Mac
    timeout_in_minutes: 90
    key: mac_fixture_5_0

  #
  # E2E Tests
  #

  # Unreal Engine 5.0 - Android
  - label: 'E2E Tests - 5.0 Android 11'
    depends_on: android_fixture_5_0
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - build/TestFixture-Android-Shipping-5.0-arm64.apk
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/build/TestFixture-Android-Shipping-5.0-arm64.apk"
          - "--appium-version=1.17.0"
          - "--device=ANDROID_11_0"
          - "--farm=bs"
          - "--order=random"
    concurrency: 5
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  # Unreal Engine 5.0 - iOS
  - label: 'E2E Tests - 5.0 iOS 12'
    depends_on: ios_fixture_5_0
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - build/TestFixture-IOS-Shipping-5.0.ipa
          - build/TestFixture-IOS-Shipping-5.0.dSYM
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/build/TestFixture-IOS-Shipping-5.0.ipa"
          - "--appium-version=1.17.0"
          - "--device=IOS_14"
          - "--farm=bs"
          - "--order=random"
    concurrency: 5
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  # Unreal Engine 5.0 - macOS
  - label: 'E2E Tests - 5.0 macOS 12'
    depends_on: mac_fixture_5_0
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.5.0:
        download:
          -  TestFixture-macOS-5.0.zip
        upload: ["maze_output/failed/**/*"]
    commands:
      - echo '--- Extracting test fixture'
      - unzip TestFixture-macOS-5.0.zip
      - echo '--- Installing dependencies'
      - bundle install
      - echo '--- Running tests'
      - bundle exec maze-runner --os=macos
