agents:
  queue: macos-12-arm

steps:
  #
  # Build Plugins
  #

  - label: 'Build Plugin - 4.27 Win 1'
    agents:
      queue: windows-general-wsl
    env:
      UE_VERSION: "4.27"
    command: features/scripts/build-plugin-wsl.sh
    artifact_paths: [Bugsnag-*.zip]
    timeout_in_minutes: 60

  - label: 'Build Plugin - 4.27 Win 2'
    agents:
      queue: windows-general-wsl
    env:
      UE_VERSION: "4.27"
    command: features/scripts/build-plugin-wsl.sh
    artifact_paths: [Bugsnag-*.zip]
    timeout_in_minutes: 60

  - label: 'Build Plugin - 4.27 Win 3'
    agents:
      queue: windows-general-wsl
    env:
      UE_VERSION: "4.27"
    command: features/scripts/build-plugin-wsl.sh
    artifact_paths: [Bugsnag-*.zip]
    timeout_in_minutes: 60

