agents:
  queue: macos-12-arm

steps:
  #
  # Build Plugins
  #

  # UE 4.27
  - label: 'Build Plugin - 4.27 Mac'
    env:
      UE_VERSION: "4.27"
      DEVELOPER_DIR: "/Applications/Xcode13.2.1.app"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - make package
    plugins:
      artifacts#v1.5.0:
        upload:
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    artifact_paths: [Build/Plugin/*.zip]
    timeout_in_minutes: 60
    key: plugin_4_27

  #
  # Build Test Fixtures
  #

  # UE 4.27
  - name: ':android: Build E2E - 4.27 Android'
    depends_on: plugin_4_27
    env:
      UE_VERSION: "4.27"
      DEVELOPER_DIR: "/Applications/Xcode13.2.1.app"
    agents:
      queue: ms-arm-12-8
    plugins:
      artifacts#v1.5.0:
        download: Build/Plugin/Bugsnag-*-UE_4.27-macOS.zip
        upload:
          - build/TestFixture-Android-Shipping-4.27-arm64.apk
          - build/TestFixture-Android-Shipping-4.27-armv7.apk
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - features/scripts/build-fixture.sh Android
    timeout_in_minutes: 60
    key: android_fixture_4_27

