agents:
  queue: opensource

steps:
  - name: 'Append Unreal 4.27 Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.4.27.yml

  - name: 'Append Unreal 5.4 Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unreal.5.4.yml

  - label: 'Conditionally trigger full set of tests'
    command: sh -c .buildkite/pipeline_trigger.sh
