agents:
  queue: macos-12-arm

steps:
  - group: ":hammer: Builds UE 5.1"
    steps:
      - label: 'Build Plugin - 5.1 macOS'
        env:
          UE_VERSION: "5.1"
          XCODE_VERSION: "13.4.1"
        commands:
          - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
          - make package
        plugins:
          artifacts#v1.5.0:
            upload:
              - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
        artifact_paths:
          - Build/Plugin/*.zip
        timeout_in_minutes: 60
        key: plugin_5_1

      - label: 'Build E2E - 5.1 Android'
        depends_on: plugin_5_1
        env:
          UE_VERSION: "5.1"
          XCODE_VERSION: "13.4.1"
        commands:
          - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
          - features/scripts/build-fixture.sh Android
        plugins:
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_5.1-macOS.zip
            upload:
              - build/TestFixture-Android-Shipping-5.1-arm64.apk
              - build/TestFixture-Android-Shipping-5.1-armv7.apk
              - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
        timeout_in_minutes: 60
        key: android_fixture_5_1

      - label: 'Build E2E - 5.1 iOS'
        depends_on: plugin_5_1
        env:
          UE_VERSION: "5.1"
          XCODE_VERSION: "13.4.1"
        commands:
          - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
          - features/scripts/build-fixture.sh IOS
        plugins:
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_5.1-macOS.zip
            upload:
              - build/TestFixture-IOS-Shipping-5.1.dSYM
              - build/TestFixture-IOS-Shipping-5.1.ipa
              - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
        timeout_in_minutes: 60
        key: ios_fixture_5_1

      - label: 'Build E2E - 5.1 macOS'
        depends_on: plugin_5_1
        env:
          UE_VERSION: "5.1"
          XCODE_VERSION: "13.4.1"
        commands:
          - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
          - features/scripts/build-fixture.sh Mac
        plugins:
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_5.1-macOS.zip
            upload:
              - TestFixture-macOS-5.1.zip
              - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
        timeout_in_minutes: 90
        key: mac_fixture_5_1

  - group: ":test_tube: E2E Tests UE 5.1"
    steps:
      - label: ':android: E2E Tests - 5.1 Android 11'
        depends_on: android_fixture_5_1
        agents:
          queue: opensource
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.3.0:
            download:
              - build/TestFixture-Android-Shipping-5.1-arm64.apk
            upload:
              - maze_output/failed/**/*
          docker-compose#v3.3.0:
            run: maze-runner
            command:
              - "--app=/app/build/TestFixture-Android-Shipping-5.1-arm64.apk"
              - "--device=ANDROID_11"
              - "--farm=bs"
              - "--order=random"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: -1
              limit: 2

      - label: 'E2E Tests - 5.1 iOS 12'
        depends_on: ios_fixture_5_1
        agents:
          queue: opensource
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.3.0:
            download:
              - build/TestFixture-IOS-Shipping-5.1.ipa
              - build/TestFixture-IOS-Shipping-5.1.dSYM
            upload:
              - maze_output/failed/**/*
          docker-compose#v3.3.0:
            run: maze-runner
            command:
              - "--app=/app/build/TestFixture-IOS-Shipping-5.1.ipa"
              - "--device=IOS_16"
              - "--farm=bs"
              - "--order=random"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: -1
              limit: 2

      - label: 'E2E Tests - 5.1 macOS 12'
        depends_on: mac_fixture_5_1
        env:
          UE_VERSION: "5.1"
          XCODE_VERSION: "13.4.1"
        timeout_in_minutes: 10
        commands:
          - echo '--- Extracting test fixture'
          - unzip TestFixture-macOS-5.1.zip
          - echo '--- Installing dependencies'
          - bundle install
          - echo '--- Running tests'
          - bundle exec maze-runner --os=macos
        plugins:
          artifacts#v1.5.0:
            download:
              - TestFixture-macOS-5.1.zip
            upload:
              - maze_output/failed/**/*
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
