agents:
  queue: macos-13-arm

steps:
  - group: ":hammer: Builds UE 5.3"
    steps:
      - label: ":macos: Build Plugin - 5.3"
        env:
          UE_VERSION: "5.3"
          XCODE_VERSION: "14.1.0"
        commands:
          - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
          - make package
        plugins:
          artifacts#v1.5.0:
            upload:
              - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
        artifact_paths:
          - Build/Plugin/*.zip
        timeout_in_minutes: 60
        key: plugin_5_3

      - label: ":android: Build E2E - 5.3"
        depends_on: plugin_5_3
        env:
          UE_VERSION: "5.3"
          XCODE_VERSION: "14.1.0"
          JAVA_VERSION: "17"
        commands:
          - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
          - features/scripts/build-fixture.sh Android
        plugins:
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_5.3-macOS.zip
            upload:
              - build/TestFixture-Android-Shipping-5.3-arm64.apk
              - build/TestFixture-Android-Shipping-5.3-armv7.apk
              - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
        timeout_in_minutes: 60
        key: android_fixture_5_3

      - label: ":ios: Build E2E - 5.3"
        depends_on: plugin_5_3
        env:
          UE_VERSION: "5.3"
          XCODE_VERSION: "14.1.0"
        commands:
          - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
          - features/scripts/build-fixture.sh IOS
        plugins:
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_5.3-macOS.zip
            upload:
              - build/TestFixture-IOS-Shipping-5.3.ipa
              - build/TestFixture-IOS-Shipping-5.3.dSYM
              - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
        timeout_in_minutes: 60
        key: ios_fixture_5_3

      #  Pending PLAT-12735
      # - label: ":mac: Build E2E - 5.3"
      #   skip: true
      #   depends_on: plugin_5_3
      #   env:
      #     UE_VERSION: "5.3"
      #     XCODE_VERSION: "14.1.0"
      #   commands:
      #     - bundle install
      #     - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      #     - features/scripts/build-fixture.sh Mac
      #   plugins:
      #     artifacts#v1.5.0:
      #       download: Build/Plugin/Bugsnag-*-UE_5.3-macOS.zip
      #       upload:
      #         - TestFixture-macOS-5.3.zip
      #         - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      #   timeout_in_minutes: 90
      #   key: mac_fixture_5_3

  - group: ":test_tube: E2E Tests UE 5.3"
    steps:
      - label: ":android: E2E Tests - 5.3 Android 12"
        depends_on: android_fixture_5_3
        agents:
          queue: opensource
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.3.0:
            download:
              - build/TestFixture-Android-Shipping-5.3-arm64.apk
            upload:
              - maze_output/failed/**/*
          docker-compose#v3.3.0:
            run: maze-runner
            command:
              - "--app=/app/build/TestFixture-Android-Shipping-5.3-arm64.apk"
              - "--device=ANDROID_12"
              - "--farm=bs"
              - "--order=random"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: -1
              limit: 2

      - label: ":ios: E2E Tests - 5.3 iOS 16"
        depends_on: ios_fixture_5_3
        agents:
          queue: opensource
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.3.0:
            download:
              - build/TestFixture-IOS-Shipping-5.3.ipa
              - build/TestFixture-IOS-Shipping-5.3.dSYM
            upload:
              - maze_output/failed/**/*
          docker-compose#v3.3.0:
            run: maze-runner
            command:
              - "--app=/app/build/TestFixture-IOS-Shipping-5.3.ipa"
              - "--device=IOS_16"
              - "--farm=bs"
              - "--order=random"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: -1
              limit: 2

      #  Pending PLAT-12735
      # - label: ":macos: E2E Tests - 5.3 macOS 14"
      #   skip: true
      #   depends_on: mac_fixture_5_3
      #   agents:
      #     queue: macos-14
      #   env:
      #     XCODE_VERSION: "14.1.0"
      #     UE_VERSION: "5.3"
      #   timeout_in_minutes: 10
      #   commands:
      #     - echo '--- Extracting test fixture'
      #     - unzip TestFixture-macOS-5.3.zip
      #     - echo '--- Installing dependencies'
      #     - bundle install
      #     - echo '--- Running tests'
      #     - bundle exec maze-runner --os=macos
      #   plugins:
      #     artifacts#v1.5.0:
      #       download:
      #         - TestFixture-macOS-5.3.zip
      #       upload:
      #         - maze_output/failed/**/*
