agents:
  queue: macos-13-arm
env:
  XCODE_VERSION: 14.1.0
  JAVA_VERSION: 11

steps:
  - label: 'Build Plugin - 5.4 Mac'
    env:
      UE_VERSION: "5.4"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - make package
    plugins:
      artifacts#v1.5.0:
        upload:
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    artifact_paths: [ Build/Plugin/*.zip ]
    timeout_in_minutes: 60
    key: plugin_5_4

  # Unreal Engine 5.4 - Android
  - name: ':android: Build E2E - 5.4 Android'
    depends_on: plugin_5_4
    env:
      UE_VERSION: "5.4"
      JAVA_VERSION: 17
    plugins:
      artifacts#v1.5.0:
        download: Build/Plugin/Bugsnag-*-UE_5.4-macOS.zip
        upload:
          - build/TestFixture-Android-Shipping-5.4-arm64.apk
          - build/TestFixture-Android-Shipping-5.4-armv7.apk
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - features/scripts/build-fixture.sh Android
    timeout_in_minutes: 60
    key: android_fixture_5_4

  # Unreal Engine 5.4 - iOS
  - name: ':ios: Build E2E - 5.4 iOS'
    depends_on: plugin_5_4
    env:
      UE_VERSION: "5.4"
    plugins:
      artifacts#v1.5.0:
        download: Build/Plugin/Bugsnag-*-UE_5.4-macOS.zip
        upload:
          - Build/TestFixture-IOS-Shipping-5.4.dSYM
          - Build/TestFixture-IOS-Shipping-5.4.ipa
          - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
    commands:
      - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
      - features/scripts/build-fixture.sh IOS
    timeout_in_minutes: 60
    key: ios_fixture_5_4

  # # Unreal Engine 5.4 - macOS
  # - name: ':mac: Build E2E - 5.4 macOS'
  #   depends_on: plugin_5_4
  #   env:
  #     UE_VERSION: "5.4"
  #   plugins:
  #     artifacts#v1.5.0:
  #       download: Build/Plugin/Bugsnag-*-UE_5.4-macOS.zip
  #       upload:
  #         - TestFixture-macOS-5.4.zip
  #         - "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
  #   commands:
  #     - rm -rf "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"
  #     - features/scripts/build-fixture.sh Mac
  #   timeout_in_minutes: 90
  #   key: mac_fixture_5_4

  # Unreal Engine 5.4 - Android
  - label: 'E2E Tests - 5.4 Android 11'
    depends_on: android_fixture_5_4
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - build/TestFixture-Android-Shipping-5.4-arm64.apk
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/build/TestFixture-Android-Shipping-5.4-arm64.apk"
          - "--device=ANDROID_11"
          - "--farm=bs"
          - "--order=random"
    concurrency: 5
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  # Unreal Engine 5.4 - iOS
  - label: 'E2E Tests - 5.4 iOS 12'
    depends_on: ios_fixture_5_4
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - build/TestFixture-IOS-Shipping-5.4.ipa
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/build/TestFixture-IOS-Shipping-5.4.ipa"
          - "--device=IOS_16"
          - "--farm=bs"
          - "--order=random"
    concurrency: 5
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  # Unreal Engine 5.4 - macOS
  # - label: 'E2E Tests - 5.4 macOS 12'
  #   depends_on: mac_fixture_5_4
  #   timeout_in_minutes: 10
  #   plugins:
  #     artifacts#v1.5.0:
  #       download:
  #         -  TestFixture-macOS-5.4.zip
  #       upload: ["maze_output/failed/**/*"]
  #   commands:
  #     - echo '--- Extracting test fixture'
  #     - unzip TestFixture-macOS-5.4.zip
  #     - echo '--- Installing dependencies'
  #     - bundle install
  #     - echo '--- Running tests'
  #     - bundle exec maze-runner --os=macos
