agents:
  queue: macos-12-arm

env:
  UE_VERSION: "4.27"
  XCODE_VERSION: "13.2.1"
  LOGS_PATH: "/Users/administrator/Library/Logs/Unreal Engine/LocalBuildLogs/*"

common_plugins: &common_plugins
  artifacts#v1.5.0:
    upload:
      - "*"

common_clean_commands: &common_clean_commands
  - rm -rf "$LOGS_PATH"

steps:
  - group: ":hammer: Builds"
    steps:
      - label: ":macos: Build Plugin - 4.27"
        key: plugin_4_27
        timeout_in_minutes: 60
        commands:
          <<: *common_clean_commands
          - make package
        plugins:
          artifacts#v1.5.0:
            upload:
              - "$LOGS_PATH"
        artifact_paths:
          - Build/Plugin/*.zip

#      - label: ":windows: Build Plugin - 4.27"
#        key: plugin_win_4_27
#        agents:
#          queue: windows-general-wsl
#        timeout_in_minutes: 60
#        command: features/scripts/build-plugin-wsl.sh
#        artifact_paths:
#          - Bugsnag-*.zip

      - label: ":android: Build E2E - 4.27"
        key: android_fixture_4_27
        depends_on: plugin_4_27
        timeout_in_minutes: 60
        commands:
          <<: *common_clean_commands
          - features/scripts/build-fixture.sh Android
        plugins:
          <<: *common_plugins
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_4.27-macOS.zip
            upload:
              - build/TestFixture-Android-Shipping-4.27-arm64.apk
              - build/TestFixture-Android-Shipping-4.27-armv7.apk

      - label: ":ios: Build E2E - 4.27"
        key: ios_fixture_4_27
        depends_on: plugin_4_27
        timeout_in_minutes: 60
        commands:
          <<: *common_clean_commands
            - features/scripts/build-fixture.sh IOS
        plugins:
          <<: *common_plugins
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_4.27-macOS.zip
            upload:
              - build/TestFixture-IOS-Shipping-4.27.dSYM
              - build/TestFixture-IOS-Shipping-4.27.ipa

      - label: ":mac: Build E2E - 4.27"
        key: mac_fixture_4_27
        depends_on: plugin_4_27
        timeout_in_minutes: 90
        commands:
          <<: *common_clean_commands
            - features/scripts/build-fixture.sh Mac
        plugins:
          <<: *common_plugins
          artifacts#v1.5.0:
            download: Build/Plugin/Bugsnag-*-UE_4.27-macOS.zip
            upload:
              - TestFixture-macOS-4.27.zip

  - group: ":test_tube: E2E Tests"
    steps:
      - label: "E2E Tests - 4.27 Android 11"
        depends_on: android_fixture_4_27
        agents:
          queue: opensource
        timeout_in_minutes: 30
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: -1
              limit: 2
        plugins:
          artifacts#v1.3.0:
            download:
              - build/TestFixture-Android-Shipping-4.27-arm64.apk
            upload:
              - maze_output/failed/**/*
          docker-compose#v3.3.0:
            run: maze-runner
            command:
              - "--app=/app/build/TestFixture-Android-Shipping-4.27-arm64.apk"
              - "--device=ANDROID_11"
              - "--farm=bs"
              - "--order=random"

      - label: "E2E Tests - 4.27 iOS 12"
        depends_on: ios_fixture_4_27
        agents:
          queue: opensource
        timeout_in_minutes: 30
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: -1
              limit: 2
        plugins:
          artifacts#v1.3.0:
            download:
              - build/TestFixture-IOS-Shipping-4.27.ipa
              - build/TestFixture-IOS-Shipping-4.27.dSYM
            upload:
              - maze_output/failed/**/*
          docker-compose#v3.3.0:
            run: maze-runner
            command:
              - "--app=/app/build/TestFixture-IOS-Shipping-4.27.ipa"
              - "--device=IOS_12"
              - "--farm=bs"
              - "--order=random"

      - label: "E2E Tests - 4.27 macOS 12"
        depends_on: mac_fixture_4_27
        timeout_in_minutes: 10
        plugins:
          artifacts#v1.5.0:
            download:
              - TestFixture-macOS-4.27.zip
            upload:
              - maze_output/failed/**/*
        commands:
          - echo '--- Extracting test fixture'
          - unzip TestFixture-macOS-4.27.zip
          - echo '--- Installing dependencies'
          - bundle install
          - echo '--- Running tests'
          - bundle exec maze-runner --os=macos
