// Generated by features/scripts/update-scenario-names.sh
static TArray<FString> ScenarioNames = {
	TEXT("BadMemoryAccessScenario"),
	TEXT("NotifyScenario"),
	TEXT("PauseSessionScenario"),
	TEXT("ResumeSessionScenario"),
};
