// Generated by features/scripts/update-scenario-names.sh
static TArray<FString> ScenarioNames = {
	TEXT("BadMemoryAccessScenario"),
	TEXT("CancelNotifyFromCallback"),
	TEXT("CancelSessionScenario"),
	TEXT("CrashAfterLaunchedScenario"),
	TEXT("GetCrumbScenario"),
	TEXT("MaxConfigCrashScenario"),
	TEXT("ModifyCrumbsScenario"),
	TEXT("ModifySessionScenario"),
	TEXT("NotifyChangingEverythingInCallback"),
	TEXT("NotifyScenario"),
	TEXT("NotifyWithLaunchInfoScenario"),
	TEXT("OpenLevelBreadcrumbsScenario"),
	TEXT("PauseSessionScenario"),
	TEXT("ResumeSessionScenario"),
	TEXT("StartWithApiKeyScenario"),
};
