// Generated by features/scripts/update-scenario-names.sh
static TArray<FString> ScenarioNames = {
	TEXT("BadMemoryAccessScenario"),
	TEXT("CancelSessionScenario"),
	TEXT("MaxConfigCrashScenario"),
	TEXT("ModifyCrumbsScenario"),
	TEXT("ModifySessionScenario"),
	TEXT("NotifyScenario"),
	TEXT("OpenLevelBreadcrumbsScenario"),
	TEXT("PauseSessionScenario"),
	TEXT("ResumeSessionScenario"),
};
